# Numpy Cheatsheet

## What is Numpy?
Numpy is a Python library used for numeric calculations Numpy supports multi dimentional arrays and methods to process the arrays. Few of the operations which are handy are:
1. Using arrays to represent vectors and then doing operations on Vectors.
2. Using 2-d array to store matrix and doing matrics lagebra.

So basically Numpy lets us store data in arrays and support algebra on these. 

## Playing around with ndarray

Numpy array is homogenenious multidimentional array. The class implementing it is called ndarray. Few basics:

1. The number of dimentions are called axis or dimention. The size of array is called length.
2. Shape shows the dimention of array as a tuple. So (m,n) where m is the number of rows and n is number of columns. So the lengh of the tuple should be the number of axis.
3. To find the data type of ndarray - a.dtype.name



In [2]:
import numpy as np
import copy

In [2]:
#lets create array with single dinemtion or axis
scores = np.array([1,2,3,4])
print(scores.ndim)
print(scores.shape)

data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(data.ndim) #should be 2
print(data.shape) # should be (4,3)
print(data.dtype.name) #/int64

1
(4,)
2
(4, 3)
int64


### Array Creation
Few ways to create array:
- `np.array([...])`
- `np.zeros((m,n))` - Create mxn array filled with zero. Argument is a tuple
- `np.empty((m,n))` - Create empty array where values are filled from memory - could have any values.
- `np.arange(start, end, step)` - Start to end element with step spacing - uses floating point.
- `np.linspace(start, end, num)` - same as arrange but tells how many element to devide the space into.

In [39]:
#lets write a helper function to print arrays
def print_array(arr):
    print(f'{arr} - type is {arr.dtype.name} has {arr.ndim} axis  and shape is {arr.shape}')

In [40]:
x = np.array(['a','b','c','d']) #initialize array from known elements
print_array(x)

y = np.zeros((3,4)) # argument is tuple - its single argument
print_array(y)

z = np.arange(1,20,3)
print_array(z)

a = np.linspace(0,20,10)
print_array(a)

['a' 'b' 'c' 'd'] - type is str32 has 1 axis  and shape is (4,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] - type is float64 has 2 axis  and shape is (3, 4)
[ 1  4  7 10 13 16 19] - type is int64 has 1 axis  and shape is (7,)
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ] - type is float64 has 1 axis  and shape is (10,)


### Indices, slices and Iteration
* Individual element can be accessed by index -> (row,column)
* Sliceing let us get subset of the array.
* We will see example of how to iterate over array in a for loop

In [41]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_array(x)

print(x[2,3]) #third row third element - should be 7

print(x[2][0::2]) # third row element index 0 to end with step of 2.

print(x[-1][0]) # last row first element - 9

#processing all rows
for row in x:
    print(row)

#process all elements
for elem in x.flat:
    print(elem)
        
#0r
for row in x:
    for i in range(row.size):
        print(row[i])
    


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] - type is int64 has 2 axis  and shape is (3, 4)
12
[ 9 11]
9
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


### Few important Functions
* Dot product. We can use `np.dot(a,b)` to find a dot product between vector and same can be used for matrix multiplication. 

In [46]:
va = np.array([1,2,3,4])
vb = np.array([5,6,7,8])

dp = np.dot(va,vb)
print(dp)

ma = np.array([[1,2],[3,4]])
mb = np.array([[5,7],[7,8]])

mc = np.dot(ma,mb)

print_array(ma)
print_array(mb)
print_array(mc)

70
[[1 2]
 [3 4]] - type is int64 has 2 axis  and shape is (2, 2)
[[5 7]
 [7 8]] - type is int64 has 2 axis  and shape is (2, 2)
[[19 23]
 [43 53]] - type is int64 has 2 axis  and shape is (2, 2)


### Problem
Given a 2-d array find the number of rows and columns in the array. To put in another words given the training set find the size of training data and number of features (assume the set does not have output variable).

In [6]:
x_train = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x_train)
print(x_train.shape)
print(f"m is {x_train.shape[0]}")
print(f"featue vector is {x_train.shape[1]}")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
m is 3
featue vector is 4


### Linear Algebra with Array
Here we can see that the original array is not mutated, hence this operation can be used safely without coping. 

In [3]:
xs = np.array([1,2,3,4])
w = 4
b = 2

output = xs * w + b

print(xs)
print(output)

[1 2 3 4]
[ 6 10 14 18]


### Copying NumPy Array - deep copy
There would be instances where we want to copy the array so that we can mutate it.

In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix_copy = copy.deepcopy(matrix)

print(matrix)
print(matrix_copy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.linspace(1, 10, 10)
print(x)
y = np.linspace(101, 110, 10)
print(y)
x_grid, y_grid = np.meshgrid(x, y, indexing="xy")
print(x_grid)
print("="*70)
print(y_grid)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[101. 102. 103. 104. 105. 106. 107. 108. 109. 110.]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[101. 101. 101. 101. 101. 101. 101. 101. 101. 101.]
 [102. 102. 102. 102. 102. 102. 102. 102. 102. 102.]
 [103. 103. 103. 103. 103. 103. 103. 103. 103. 103.]
 [104. 104. 104. 104. 104. 104. 104. 104. 104. 104.]
 [105. 105. 105. 105. 105. 105. 105. 105. 105. 105.]
 [106. 106. 106. 106. 106. 106. 106. 106. 106. 106.]
 [107. 107. 107. 107. 107. 107. 107. 107. 107. 107.]
 [108. 108. 108. 108. 108. 108. 108. 108. 108. 108.]
 [109. 109. 109. 109. 109. 109. 109. 109. 109. 109.

In [15]:
heights = np.array([154, 155, 156, 157, 158, 159, 160, 161, 162, 163])
ages = np.array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
eligible = ages > 25
print(eligible)
print(heights[eligible])
print(heights[~eligible])



[False False False False False False  True  True  True  True]
[160 161 162 163]
[154 155 156 157 158 159]
